### ISSUE TITLE
기타 버그들

### ISSUE THREAD

**Issue by sdondon** [yapp-project/team06#17]
- [x] 현재위치- 지역설정검색하기 - 검색시 튕김 (동 검색시 튕김, 다른 것도 확인 필요)
- [x] 현재위치로 날씨보기 - 적용 안됨. 확인 필요
- [x] 피드백 보내지 > 피드백 보내기 오타 정정
- [x] 이름 변경 - 변경후 수정 안됨 / 초기 설정한 이름이랑 다름
- [x] 로그아웃 - 적용 안되는 중 - 로그아웃시 처음 SNS 가입 화면으로 돌아가게 바꾸기

**Comment by YooCheaHwa** [comment]
> 이름 변경 - 변경후 수정 안됨 / 초기 설정한 이름이랑 다름  
* 이부분 헷갈릴 수 있을 것 같아 추가 설명 붙입니다>  - 현재 이름변경 후 변경된 이름으로 수정이 안되는 상태이므로 변경한 이름으로 수정될 수 있도록 작업 필요합니다

**Comment by YooCheaHwa** [comment]
> 설정 - 이름 변경 버튼, 연필모양 아이콘 - ㅁㅁㅁ님에서 ‘님’ 탭할 시 설정창이 닫힘 - 닫히지 않게 조정

**Comment by YooCheaHwa** [comment]
> 입력필드에 플레이스 홀더 문장 : 날씨왕에 도전해보세요! > 오늘의 날씨를 한마디로 말해주세요 로 수정
![image](https://user-images.githubusercontent.com/51351893/58944538-00976000-87bd-11e9-85fd-945452a245d1.png)

**Comment by sdondon** [comment]
이름 변경 - 서버측 작업이 필요합니다. 
정상적으로 요청 후에도 변경이 안됨
