### ISSUE TITLE
인터렉션 관련 추가 수정 사항

### ISSUE THREAD

**Issue by sdondon** [yapp-project/team06#23]
- [x] 설정창 열린 상태에서는 메인-카드 스와이프 정지되게
- [x] 설정창 인터렉션 - 열리고 닫히는 부분 현재 위 영역만됨 - 아래영역도 스와이프 가능하게 	(*단위, 알림설정, 피드백 보내기, 앱평가하기 터치 영역 오른쪽 끝까지 잡혀있어서 그런듯. 확인 필요)
- [x] 설정창 인터렉션2 - 닫힐때 설정창 밖 메인부분 터치시 자동으로 닫히게도 필요 (사용성위해)

**Comment by YooCheaHwa** [comment]
메인 -> 날씨톡톡 열기 방법:
  **_1) 탭하기 (*이부분 인터렉션 필요)_**
  2) 끌어올리기
